language: python
sudo: false
python:
    - "3.5"
install:
    - pip install -r requirements.txt --upgrade
script:
    - ./manage.py makemigrations
    - ./manage.py migrate
    - ./manage.py test configurator
